### ISSUE TITLE
small typo in README.md file

### ISSUE THREAD

**Issue by Arna-Maity** [watz0n/learn-rv32i-asap#1]
@watz0n There are some few minor typos in the README.md file. Do you want me to correct them?

**Comment by watz0n** [comment]
Hi @Arna-Maity , thanks your review. Welcome to correct these typos, because I'm not native speaker and still learning how to express in English.

**Comment by Arna-Maity** [comment]
Hi @watz0n, i have made the necessary changes and opened a PR. Could you please review it?

**Comment by watz0n** [comment]
Hi Arna,

I have urgent task from current employer, I may review it in this weekend.
Sorry about my late reply, and thank you for your help.

Many thanks,
Watson

**Comment by Arna-Maity** [comment]
Closing this issue
